<?php

namespace frontend\modules\api\models;

use common\models\User;

/**
 * This is the model class for table "task".
 * @property int    $id
 * @property string $title
 * @property string $description
 * @property int    $project_id
 * @property int    $executor_id
 * @property int    $started_at
 * @property int    $completed_at
 * @property int    $creator_id
 * @property int    $updater_id
 * @property int    $created_at
 * @property int    $updated_at
 * @property User   $executor
 * @property User   $creator
 * @property User   $updater
 */
class Task extends \common\models\Task
{
    public function extraFields() {
        return parent::extraFields(); // TODO: Change the autogenerated stub
    }

    /**
     * @return array|false
     */
    public function fields() {
        return [
            'id',
            'title',
            'description_short' => function (Task $model) {
                //description_short (обрезанный до 50 символов description);
                //не ВЕРНУТЬ до 50 символов, а ОБРЕЗАТЬ до 50. Т.е. длина = 50
                return substr($model->description, 0, 50);
            }
        ];
    }

}
