<?php

namespace frontend\modules\api\models;

/**
 * User model
 * @property integer $id
 * @property string  $username
 * @property string  $password_hash
 * @property string  $password_reset_token
 * @property string  $email
 * @property string  $auth_key
 * @property integer $status
 * @property integer $created_at
 * @property integer $updated_at
 * @property string  $password write-only password
 * @property Task[]  $tasks
 */
class User extends \common\models\User
{
    public function extraFields() {
        return parent::extraFields(); // TODO: Change the autogenerated stub
    }

    /**
     * @return array|false
     */
    public function fields() {
        return [
        ];
    }

}
